#!/bin/bash

echo "Enter the first number : "
read a
echo "Enter the second number : "
read b
sum=$((a+b))
diff=$((a-b))
prod=$((a*b))
div=$((a/b))

echo "sum = $sum"
echo "difference = $diff"
echo "product = $prod"
echo "division = $div"
